name: Deploy to Heroku

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh    
      - uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "shrouded-reaches-06600"
          heroku_email: sebasandres0694@gmail.com
          justlogin: true

      - name: Set Heroku Config Vars
        run: |
          heroku config:set DATABASE_URL="${{ secrets.DATABASE_URL }}" -a shrouded-reaches-06600
          heroku config:set DATABASE_USER="${{ secrets.DATABASE_USER }}" -a shrouded-reaches-06600
          heroku config:set DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" -a shrouded-reaches-06600
          heroku config:set DATABASE_HOST="${{ secrets.DATABASE_HOST }}" -a shrouded-reaches-06600
          heroku config:set DATABASE_PORT="${{ secrets.DATABASE_PORT }}" -a shrouded-reaches-06600
          heroku config:set CERTIFICATE_VALUE="${{ secrets.CERTIFICATE_VALUE }}" -a shrouded-reaches-06600
          heroku config:set ACCESS_JWT_SECRET="${{ secrets.ACCESS_JWT_SECRET }}" -a shrouded-reaches-06600
          heroku config:set REFRESH_JWT_SECRET="${{ secrets.REFRESH_JWT_SECRET }}" -a shrouded-reaches-06600
          heroku config:set SESSION_SECRET="${{ secrets.SESSION_SECRET }}" -a shrouded-reaches-06600
          heroku config:set ADMIN_PASSWORD="${{ secrets.ADMIN_PASSWORD }}" -a shrouded-reaches-06600
          heroku config:set ADMIN_USERNAME="${{ secrets.ADMIN_USERNAME }}" -a shrouded-reaches-06600
          heroku config:set ADMIN_EMAIL="${{ secrets.ADMIN_EMAIL }}" -a shrouded-reaches-06600
          heroku config:set GOOGLE_CLIENT_ID="${{ secrets.GOOGLE_CLIENT_ID }}" -a shrouded-reaches-06600
          heroku config:set GOOGLE_CLIENT_SECRET="${{ secrets.GOOGLE_CLIENT_SECRET }}" -a shrouded-reaches-06600

      - name: Deploy to Heroku
        run: |
          git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/shrouded-reaches-06600.git || true
          git push heroku `git subtree split --prefix server main`:main --force
