name: Deployment to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        API_KEY: ${{ secrets.API_KEY }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
        ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
        ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
        API_HOST: ${{ secrets.API_HOST }}
        DB_PATH: ${{ vars.DB_PATH }}
        MIGRATIONS_PATH: ${{ vars.MIGRATIONS_PATH }}
        SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
        REFRESH_JWT_SECRET: ${{ secrets.REFRESH_JWT_SECRET }}
        ACCESS_JWT_SECRET: ${{ secrets.ACCESS_JWT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
        DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
        DATABASE_USER: ${{ secrets.DATABASE_USER }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        CERTIFICATE_VALUE: ${{ secrets.CERTIFICATE_VALUE }}
    defaults:
      run:
        working-directory: server
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v4

      - name: Setup Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Download all dependencies
        run: |
          npm install

      - name: Build the project
        run: |
          npm run parcel-build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "backend-house-searcher" #Must be unique in Heroku
          heroku_email: "sebasandres0694@gmail.com"
          procfile: "web: npm run start"
        env:
            HD_API_KEY: ${{ secrets.API_KEY }}
            HD_ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
            HD_ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
            HD_ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
            HD_API_HOST: ${{ secrets.API_HOST }}
            HD_DB_PATH: ${{ vars.DB_PATH }}
            HD_MIGRATIONS_PATH: ${{ vars.MIGRATIONS_PATH }}
            HD_SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
            HD_REFRESH_JWT_SECRET: ${{ secrets.REFRESH_JWT_SECRET }}
            HD_ACCESS_JWT_SECRET: ${{ secrets.ACCESS_JWT_SECRET }}
            HD_GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
            HD_GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
            HD_TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
            HD_TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
            HD_DATABASE_HOST: ${{ secrets.DATABASE_HOST }}
            HD_DATABASE_PORT: ${{ secrets.DATABASE_PORT }}
            HD_DATABASE_USER: ${{ secrets.DATABASE_USER }}
            HD_DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
            HD_CERTIFICATE_VALUE: ${{ secrets.CERTIFICATE_VALUE }}
