name: Docker Image CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY: ${{ secrets.API_KEY }}
      ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      ADMIN_USERNAME: ${{ secrets.ADMIN_USERNAME }}
      ADMIN_EMAIL: ${{ secrets.ADMIN_EMAIL }}
      API_HOST: ${{ secrets.API_HOST }}
      DB_PATH: ${{ vars.DB_PATH }}
      MIGRATIONS_PATH: ${{ vars.MIGRATIONS_PATH }}
      SESSION_SECRET: ${{ secrets.SESSION_SECRET }}
      REFRESH_JWT_SECRET: ${{ secrets.REFRESH_JWT_SECRET }}
      ACCESS_JWT_SECRET: ${{ secrets.ACCESS_JWT_SECRET }}
      GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
      GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
      TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
      TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      
    defaults:
      run:
        working-directory: server

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --build-arg API_KEY=${API_KEY} --build-arg ADMIN_PASSWORD=${ADMIN_PASSWORD} --build-arg ADMIN_USERNAME=${ADMIN_USERNAME} --build-arg ADMIN_EMAIL=${ADMIN_EMAIL} --build-arg API_HOST=${API_HOST} --build-arg DB_PATH=${DB_PATH} --build-arg MIGRATIONS_PATH=${MIGRATIONS_PATH} --build-arg SESSION_SECRET=${SESSION_SECRET} --build-arg REFRESH_JWT_SECRET=${REFRESH_JWT_SECRET} --build-arg ACCESS_JWT_SECRET=${ACCESS_JWT_SECRET} --build-arg GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID} --build-arg GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET} --build-arg TEST_USER_EMAIL=${TEST_USER_EMAIL} --build-arg TEST_USER_PASSWORD=${TEST_USER_PASSWORD} . --file Dockerfile --tag my-own-app:$(date +%s)

    - name: Push the Docker image
      run: docker push my-own-app:$(date +%s)
